### ISSUE TITLE
How can I make CSS hover effects touch-friendly?

### ISSUE THREAD

**Issue by vmcosta** [ciar4n/imagehover.css#10]
Great stuff,
I'm just having a small big issue, it works great on desktop devices, but on mobile ones the hover effects do not trigger, any way to achieve that?

Thanks

**Comment by ciar4n** [comment]
Hello

Presuming your device allows touch to hover. You should be able to touch your images to trigger the hover effect?

Ciarán

**Comment by C-Lodder** [comment]
Touch devices do not use a mouseover/mouseenter/hover event listener. You'll need to "tap" on the image to trigger this.
