### ISSUE TITLE
Error with boostrap modal

### ISSUE THREAD

**Issue by ghost** [ciar4n/imagehover.css#11]
I have a code 

```
<figcaption>
.....
<a href="#" data-toggle="modal" data-target="#module-detail-modal" class="view-profile" title="">Intall Module</a>
</figcaption>
```

And I have a modal boostrap. When I click to open modal, close modal, imagehover not working rigth

Please help me! Thank you so much!

**Comment by C-Lodder** [comment]
@cuongduong257 Please can you create a Codepen or JSFiddle?

**Comment by C-Lodder** [comment]
Closing for now, can be reopened if still an issue
