### ISSUE TITLE
Could you help add git tag?

### ISSUE THREAD

**Issue by kennynaoh** [ciar4n/imagehover.css#12]
Hello @ciar4n I am the member of cdnjs project. We want to host this library. Git tag can help us to know your release version, and we can auto-update the version when you have new release. Could you please help us add git tag. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/10046

**Comment by ciar4n** [comment]
Hi @kennynaoh 

Certainly. A git tag has been added as requested. Let me know if you need anything else.

Regards
Ciarán

**Comment by kennynaoh** [comment]
@ciar4n Thanks for your help. I will host this library on CDNJS ASAP.
