### ISSUE TITLE
Transparent background on figcaption

### ISSUE THREAD

**Issue by ericabao** [ciar4n/imagehover.css#13]
Hi guys any idea how to make an rgba background works? I have tried it but it seems not working... I just want to use a semi transparent figcaption background.

**Comment by ciar4n** [comment]
Hello

Using semi transparent backgrounds will vary depending on the effect. Which effect are you using?

Ciarán

**Comment by oscarkwan** [comment]
Which effects work for transparent?

**Comment by marchandrs** [comment]
one year later, still waiting

**Comment by ciar4n** [comment]
The background element to the caption on hover varies from effect to effect. In most cases the following will work which covers most elements. Note in some cases the backgound image has been transformed to be no longer available or no longer front facing. 

```
[class^="imghvr-"] figcaption, 
[class*=" imghvr-"] figcaption,
[class^="imghvr-"]:before, 
[class*=" imghvr-"]:before,
[class^="imghvr-"]:after, 
[class*=" imghvr-"]:after {
	background-color: rgba(19, 87, 150, .5) !important;	
}
```

Where `19, 87, 150` is the RGB color and `.5` is the transparency.

Ciaran

**Comment by marchandrs** [comment]
will test it in my project when i get home, thank you :D
