### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by amt925** [ciar4n/imagehover.css#19]
It would be great if this was available on npm and even yarn too.

### Publishing a Package on npm:
https://docs.npmjs.com/getting-started/publishing-npm-packages#publishing-the-package

### Publishing a Package on Yarn:
https://yarnpkg.com/lang/en/docs/publishing-a-package/#toc-publishing-your-package

**Comment by ciar4n** [comment]
Imagehover is available on npm with `npm install imagehover.css`
