### ISSUE TITLE
Prefixing with Bourbon is deprecated, any plans of using Autoprefixer?

### ISSUE THREAD

**Issue by manikbajaj** [ciar4n/imagehover.css#23]
WARNING: [Bourbon] [Deprecation] `animation-name` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.

I get this error while compiling SASS. Which is self-explanatory and can be fixed by using Autoprefixer in Gulp as you are already using Gulp. I can contribute some time to help fix this if needed and if you guys plan to do it would be great !!  

In fact, don't you think bourbon should be removed as a dependency all together? I mean using lesser code and creating mixins that are needed and leaving Auprefixing to gulp?

**Comment by C-Lodder** [comment]
I'll sort out a PR for autoprefixer and custom mixins within the next couple of days.

**Comment by manikbajaj** [comment]
Cool sounds good!! For now, I have set the `$output-bourbon-deprecation-warnings: false;` to suppress the warnings and will look forward on an update !!

**Comment by C-Lodder** [comment]
@manikbajaj Just remembered I removed Bourbon in this PR: https://github.com/ciar4n/imagehover.css/pull/21

Problem being is there hasn't been a release for this in a long time, so I'll get v2.0.0 released in the next couple of hours.

**Comment by manikbajaj** [comment]
Cool! Sounds good :) 
Also if you can have an extended license for developers to ship it along with a large product such as WordPress theme etc it would be great, just the way IsotopeJs does it!! If you have something similar on the roadmap I would be interested. Let me know!

**Comment by C-Lodder** [comment]
It comes under the MIT license (https://github.com/ciar4n/imagehover.css/blob/master/LICENSE) which allows you to use in in free or commercial products.

I'm not sure about the extended version of imagehover.css which is a paid product. Perhaps @ciar4n can shed some light on that.

**Comment by C-Lodder** [comment]
Released v2.0.0 https://github.com/ciar4n/imagehover.css/releases/tag/v2.0.0

@ciar4n will publish to NPM a little later
