### ISSUE TITLE
SCSS Support

### ISSUE THREAD

**Issue by anhskohbo** [ciar4n/imagehover.css#3]
Could be nice if imagehover support SCSS.
Thanks for great project :)

**Comment by niceoutput** [comment]
It will be amazing if you support SASS.
Nice effects by the way .

**Comment by ciar4n** [comment]
Working on this at the moment so all going well we should have SCSS support added shortly.

Ciarán

**Comment by niceoutput** [comment]
Sounds great, thanks .

**Comment by ciar4n** [comment]
Initial SCSS support has been added as requested.

Ciarán

**Comment by anhskohbo** [comment]
Thanks!
