### ISSUE TITLE
How about compatibility?

### ISSUE THREAD

**Issue by stuxt** [ciar4n/imagehover.css#5]
RT.
How about compatibility?
In different browsers or terminal devices.

**Comment by marcobiedermann** [comment]
> Imagehover.css relies heavily on some CSS3 features including pseudo-elements, animations, transitions and transforms. Some older browsers will have limited support of these features.

You could check [Can I Use](http://caniuse.com/) for browser support:
- [Animations](http://caniuse.com/#feat=css-animation)
- [Transitions](http://caniuse.com/#feat=css-transitions)
- [Transform2d](http://caniuse.com/#feat=transforms2d)
- [Transform3d](http://caniuse.com/#feat=transforms3d)

**Comment by stuxt** [comment]
Thx
