### ISSUE TITLE
Links redirects to 404 page

### ISSUE THREAD

**Issue by tcelestino** [ciar4n/imagehover.css#7]
When I try to download this project in website, the links below redirect me for 404 page.

http://imagehover.io/bicexternal/https://github.com/ciar4n/imagehover.css/archive/master.zip
http://imagehover.io/bicexternal/https://github.com/ciar4n/imagehover.css

**Comment by ciar4n** [comment]
Hello

This appears to be an issue if you have accessed the site via the Frontend Buzz news letter. To amend try accessing imagehover.io directly.. http://imagehover.io/

Ciarán
