### ISSUE TITLE
Bower/NPM support 

### ISSUE THREAD

**Issue by webdevsuperfast** [ciar4n/imagehover.css#8]
Awesome work. Can you please add bower/npm support? Currently I'm using `bower install https://github.com/ciar4n/imagehover.css.git` to install it via bower.

**Comment by ozzyogkush** [comment]
I second this request (using NPM). Just found this and want to grab it for a project, but it cries because there is no `package.json`.

**Comment by ciar4n** [comment]
Thank you for the suggestions.

Bower support has been added (bower install imagehover.css). NPM to follow.

Ciarán

**Comment by webdevsuperfast** [comment]
Thanks for adding Bower support @ciar4n.
